import '@radix-ui/themes/styles.css';
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes';
import './globals.css'


import NavBar from '../lib/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Theme appearance="dark" accentColor="bronze">  {children} </Theme>
      </body>
    </html>
  )
}
